name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      YANDEX_MAPS_API_KEY: ${{ secrets.YANDEX_MAPS_API_KEY }}
      YANDEX_MAPS_ROUTER_API_KEY: ${{ secrets.YANDEX_MAPS_ROUTER_API_KEY }}
      NUXT_UPLOADTHING_TOKEN: ${{ secrets.NUXT_UPLOADTHING_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build Nuxt
        run: bun run build

      - name: ESLint
        run: bun lint
